use a stronger password that passes strength cehck in FIPS mode bsc#1…
openSUSE/pesign-obs-integration pull request #54
Opened 2024-07-30 07:46 UTC by msmeissn

…228433

2025-02-11 17:34 UTC, dirkmueller commented on pesign-repackage.spec.in
> +echo Eir4;Qua.daeJ,hP0 > "$nss_db/passwd"
quoting missing?

this leads to 

```shell
echo Eir4;Qua.daeJ,hP0
Eir4
bash: Qua.daeJ,hP0: command not found
```

2025-02-11 17:34 UTC, dirkmueller requested changes
@msmeissn  please quote the password or use one that only has safe characters

2025-02-12 11:09 UTC, msmeissn commented
fixed above

2025-02-12 20:52 UTC, dirkmueller commented on brp-99-pesign
> +echo Eir4;Qua.daeJ,hP0 > "$nss_db/passwd"
```suggestion
echo 'Eir4;Qua.daeJ,hP0' > "$nss_db/passwd"
```

2025-02-14 09:51 UTC, dirkmueller approved these changes

2025-02-14 09:51 UTC, merged